# Generated by Django 3.2.25 on 2024-06-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scl_management', '0002_dept_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('DEPT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scl_management.dept_table')),
            ],
        ),
    ]
