# Generated by Django 3.2.25 on 2024-06-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scl_management', '0003_course_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('sem', models.BigIntegerField()),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scl_management.course_table')),
            ],
        ),
    ]
