# Generated by Django 3.2.25 on 2024-06-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scl_management', '0004_sub_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('img', models.FileField(upload_to='')),
                ('DEPT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scl_management.dept_table')),
            ],
        ),
    ]
