# Generated by Django 3.2.25 on 2024-06-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scl_management', '0005_staff_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_table',
            old_name='Name',
            new_name='stf_name',
        ),
        migrations.AddField(
            model_name='staff_table',
            name='gender',
            field=models.CharField(default=5, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='stud_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('sem', models.BigIntegerField()),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scl_management.course_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scl_management.login_table')),
            ],
        ),
    ]
