# Generated by Django 3.2.25 on 2024-06-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scl_management', '0006_auto_20240626_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scl_management.staff_table')),
                ('SUB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scl_management.sub_table')),
            ],
        ),
    ]
