# Generated by Django 3.2.25 on 2024-06-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scl_management', '0007_notes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scl_management.staff_table')),
                ('SUB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scl_management.sub_table')),
            ],
        ),
    ]
