# Generated by Django 3.2.25 on 2024-06-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scl_management', '0008_assign_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_table',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scl_management.login_table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stud_table',
            name='img',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
