# Generated by Django 3.2.25 on 2024-06-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scl_management', '0009_auto_20240627_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_table',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stud_table',
            name='phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
